### ISSUE TITLE
Support for multiple xmpp accounts

### ISSUE THREAD

**Issue by grafenhofer** [anewusername/mxpp#11]
Support for multiple xmpp accounts would allow to migrate multiple users from xmpp to matrix. For example:

@user1:newmatrixserver.com <---> user1@oldxmppserver.com
@user2:newmatrixserver.com <---> user2@oldxmppserver.com
etc.

**Comment by anewusername** [comment]
I usually handle this by running multiple instances of the bot -- is there any use case that isn't handled by doing so?
