### ISSUE TITLE
Inverse design algorithm

### ISSUE THREAD

**Issue by jiehuang008** [anewusername/mxpp#6]
Hi, I'm Jie Huang, a PHD student from China. I'm very intesested in your inverse design algorithm.

**Comment by anewusername** [comment]
Hi Jie,

Most of my public photonics-related code is on my personal site ( https://mpxd.net/janp/software.html and https://mpxd.net/gogs ). I don't currently have any publicly available inverse design software, but I have written open-source packages for many of the necessary components (e.g. Yee grid generation, fast FDTD and FDFD implementations, waveguide mode solver, etc.).
